description: A VNC / Remote Framebuffer / RFC 6143 client purely written in Dart/Flutter
homepage: https://github.com/Goddchen/flutter-vnc
name: flutter_rfb
repository: https://github.com/Goddchen/flutter-vnc
version: 0.7.0

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dart_rfb:
    path: ../dart-rfb
  flutter:
    sdk: flutter
  fpdart: ^0.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logging: ^1.1.0
  stream_transform: ^2.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2

flutter:
